### PR TITLE
Tried to group the content. Removed unnecesssary content.

### PR DESCRIPTION
**Pull request by BreimerR**
All changes were made on the Beginner track.

### CODE REVIEW

**Comment by Nyamador** [comment]
Looking Good @BreimerR , It would be really great if you correct the inconsistencies with the use of Html and Markdown.

Might be a little confusing for anyone who tries to contribute after you.🙂

**Comment by BreimerR** [comment]
Using the grouping with non-md design was quite tedious. But I think the latest commit solves some of these issues since phase 2 content is basically phased 1 content. Removing the need to group the content.

**Comment by mikeattara** [comment]
@BreimerR, kindly use Markdown syntax. I can still see HTML syntax in the document. Thanks

**Comment by BreimerR** [comment]
Html Removed

**Pull request closed without merging**
